name: vertical_card_pager_view
description: "Vertical Card Pager View for Flutter"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/vertical_card_pager_view

version: 1.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  vertical_card_pager: #@add

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more: #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/vertical_card_pager_view/
  uses-material-design: true